version: '3'
services:
    # Название сервиса
    server:
        build:
          # Путь к директории, содержащей файл Dockerfile
          context: ./
        # Название образа
        image: words_solver_cv_server
        # Название контейнера
        container_name: words_solver_cv
        # Перенаправление порта [порт компьютера]:[порт контейнера]
        ports:
            - "50000:50000"
        # Данная инструкция сообщает докеру, что контейнер
        # должен прослушивать данный порт во время выполнения
        expose:
            - "50000"